### ISSUE TITLE
Support for Safari?

### ISSUE THREAD

**Issue by bmcorser** [oliverzheng/howtocenterincss#38]
Cool site, coming from InDesign etc I was always bemused by how difficult it was to do "simple" layout things in CSS. I didn't test on IE (no Windows box) but Chrome and Firefox produced the output I was expecting, but Safari didn't ...

I don't see any mention of Safari on the site, so perhaps you don't intend to support it? It appears that Safari doesn't support `flex`. Crappy gif video showing what I mean:
![howtocenterincss-safari](https://cloud.githubusercontent.com/assets/1449387/9387466/8c32638e-4758-11e5-931b-545258eac643.gif)

``` css
      #app-loading {
        background: white;
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        display: flex;
        justify-content: center;
        align-items:center;
        font-size: 2em;
      }
```
